sudo: 'required'

language: python
python:
  - "3.6"

# needed for the docker pipe
services:
- docker

git:
  depth: 1

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build
      script: bash ./build.sh
